config/routes.rb
Rails.application.routes.draw do
  root :to => "messages#index"
  resources :messages, :except => [:new, :edit, :create] do
	post 'reply', on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  before_update :update_gmail
  before_destroy :delete_email

  def update_gmail
    email = Gmailer.gmail.inbox.find(:msg_id => self.message_id).first
    return false unless email

    if self.read_changed?
      email.send(self.read ? :read! : :unread!)
    end

    if self.star_changed?
      email.send(self.star ? :star! : :unstar!)
    end
  end

  def delete_email
    email = Gmailer.gmail.inbox.find(:all).find{|d| d.msg_id == self.message_id}
    email && email.delete!
  end

  def self.refresh!
    Gmailer.gmail.inbox.emails(:all).each do |email|
      if message = self.find_by_message_id(email.msg_id)
        Rails.logger.info "Updaing mail with id #{email.msg_id}"
        #TODO: handle failed update
        message.update_columns(label: email.labels.to_s, read: email.read?, star: email.starred?)
      else
        Rails.logger.info "Creating new mail with id #{email.msg_id}"
        self.create(
          message_id: email.msg_id,
          body: email.message.body,
          label: email.labels.to_s,
          to: email.message.to,
          from: email.message.from,
          subject: email.message.subject,
          date: email.date,
          read: email.read?,
          star: email.starred?
        )
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :update, :destroy, :reply]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    email = Gmailer.gmail.inbox.find(:all).find {|e| e.msg_id == @message.message_id.to_i } #convert due to wrong type
    @attachments = email ? email.message.attachments : []
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { redirect :back }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def reply
    message = @message
    message_body = params[:message][:body]
    email = Gmailer.gmail.compose do
      to message.from[2..-3]
      subject message.subject
      text_part do
        body message_body
      end
    end
    email.deliver!

    #do nothing for now
    redirect_to @message, notice: 'Reply sent.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:read, :star)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
	def print_bold_if_unread(message, field)
		value = message.send(field)
		raw message.read ? value : "<b>#{value}</b>"
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GmailClient</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message, local: true) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :message_id %>
    <%= form.text_field :message_id, id: :message_message_id %>
  </div>

  <div class="field">
    <%= form.label :from %>
    <%= form.text_field :from, id: :message_from %>
  </div>

  <div class="field">
    <%= form.label :to %>
    <%= form.text_field :to, id: :message_to %>
  </div>

  <div class="field">
    <%= form.label :subject %>
    <%= form.text_field :subject, id: :message_subject %>
  </div>

  <div class="field">
    <%= form.label :label %>
    <%= form.text_field :label, id: :message_label %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :message_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inbox</h1>

<table>
  <thead>
    <tr>
      <th>From</th>
      <th>Subject</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= link_to print_bold_if_unread(message, :from), message %></td>
        <td><%= link_to print_bold_if_unread(message, :subject), message %></td>
        <td><%= print_bold_if_unread(message, :date) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>From:</strong>
  <%= @message.from %>
</p>

<p>
  <strong>To:</strong>
  <%= @message.to %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @message.subject %>
</p>

<p>
  <strong>Label:</strong>
  <%= @message.label %>
</p>

<p>
  <strong>Attachments:</strong>
  <% @attachments.each do |attachment| %>
    <%= attachment.filename %>
  <% end %>
</p>

<p>
  <strong>Actions:</strong>
  <%= link_to 'Delete', @message, method: :delete, data: { confirm: 'Are you sure?' } %>
  <%= link_to (@message.star ? "UnStar" : "Mark as star"), message_path(@message, :message => {:star => !@message.star}), :method=> :put %>
  <%= link_to (@message.read ? "UnRead" : "Mark as read"), message_path(@message, :message => {:read => !@message.read}), :method=> :put %>
</p>

<p>
  <strong>Body:</strong>
  <pre>
    <%= raw @message.body %>
  </pre>
</p>

<%= form_for @message, url: reply_message_path(@message), method: "post" do |message| %>
  <%= message.text_area :body, cols: 80, rows: 10 %>
  </br>
  <%= message.submit "Reply" %>
<% end %>

</br>
<%= link_to 'Back', messages_path %>